"""empty message

Revision ID: 5676eac1bac1
Revises: 
Create Date: 2024-01-29 14:41:50.608245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5676eac1bac1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_pipeline_id'), 'pipeline', ['id'], unique=False)
    op.create_table('pipeline_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('handler', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_pipeline_step_id'), 'pipeline_step', ['id'], unique=False)
    op.create_table('pipeline_step_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_step_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('step_order > 0'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_step_id'], ['pipeline_step.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'pipeline_step_id', 'step_order')
    )
    op.create_index(op.f('ix_pipeline_step_association_id'), 'pipeline_step_association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_step_association_id'), table_name='pipeline_step_association')
    op.drop_table('pipeline_step_association')
    op.drop_index(op.f('ix_pipeline_step_id'), table_name='pipeline_step')
    op.drop_table('pipeline_step')
    op.drop_index(op.f('ix_pipeline_id'), table_name='pipeline')
    op.drop_table('pipeline')
    # ### end Alembic commands ###
