"""empty message

Revision ID: a27c8b062879
Revises: 49df01e0c05e
Create Date: 2024-02-01 17:12:14.579168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27c8b062879'
down_revision: Union[str, None] = '49df01e0c05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_task', 'status',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_task', 'status',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)
    # ### end Alembic commands ###
